spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/libraryloop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:libraryuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:librarypass}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

api.security.token.secret=${JWT_SECRET:iaowhfdoawfhoqui32gho1ubg24ou1ivb24oi}

spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=500,expireAfterAccess=10m